#!/usr/bin/env bash
# Initialize counter
counter=0

# Using an until loop to display "Best School" 10 times
until [ $counter -ge 10 ]
do
    echo "Best School"
    
    # Increment counter
    ((counter++))
done
