#!/usr/bin/env bash
# Initialize counter
counter=1

# Using a while loop to display "Best School" 10 times
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    # Increment counter
    ((counter++))
done
